/// Golden Rules enforcement tests — generated by spine-rules.
use spine_rules::golden_rules_suite;

golden_rules_suite! {
    binary: env!("CARGO_BIN_EXE_shape"),
    operator_json: include_str!("../operator.json"),
    source_files: &[
        "src/refusal/codes.rs",
        "src/refusal/payload.rs",
        "src/orchestrator.rs",
        "src/scan.rs",
        "src/output/json.rs",
        "src/capsule/mod.rs",
        "src/capsule/min_repro.rs",
    ],
}
